/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 oldpc.glb 
Author: anarki3000 (https://sketchfab.com/anarki3000)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/old-pc-f0dca426be374fba96af9675799f9855
Title: Old PC
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/oldpc.glb");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group position={[0, 0, 20]}>
          <mesh
            geometry={nodes.Object_5.geometry}
            material={materials.VoxMaterial_64}
          />
          <mesh
            geometry={nodes.Object_6.geometry}
            material={materials.VoxMaterial_72}
          />
          <mesh
            geometry={nodes.Object_7.geometry}
            material={materials.VoxMaterial_86}
          />
          <mesh
            geometry={nodes.Object_8.geometry}
            material={materials.VoxMaterial_87}
          />
          <mesh
            geometry={nodes.Object_9.geometry}
            material={materials.VoxMaterial_88}
          />
          <mesh
            geometry={nodes.Object_10.geometry}
            material={materials.VoxMaterial_95}
          />
          <mesh
            geometry={nodes.Object_11.geometry}
            material={materials.VoxMaterial_96}
          />
          <mesh
            geometry={nodes.Object_12.geometry}
            material={materials.VoxMaterial_112}
          />
          <mesh
            geometry={nodes.Object_13.geometry}
            material={materials.VoxMaterial_128}
          />
          <mesh
            geometry={nodes.Object_14.geometry}
            material={materials.VoxMaterial_136}
          />
          <mesh
            geometry={nodes.Object_15.geometry}
            material={materials.VoxMaterial_160}
          />
          <mesh
            geometry={nodes.Object_16.geometry}
            material={materials.VoxMaterial_168}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/oldpc.glb");
